const Portfolio_data = [
  {
    id: 1,
    category: "3D",
    totalLike: "600",
    title: "3D modelling",
    image: "https://th.bing.com/th/id/OIP.ZTneTykQDsu6-rjMrG8xjAHaG1?pid=ImgDet&rs=1",
  },
  {
    id: 2,
    category: "APPLICATION",
    totalLike: "750",
    title: "Mechanical Drafting",
    image: "https://i.pinimg.com/474x/eb/61/a9/eb61a96fc42530bb3e6fe85c5e95b00f--robot-arm-cyborg.jpg",
  },
  {
    id: 3,
    category: "PHOTOSHOP",
    totalLike: "630",
    title: "Assembly Design ",
    image: "https://i.ytimg.com/vi/kd1abyeyHcM/maxresdefault.jpg",
  },
  {
    id: 4,
    category: "FIGMA",
    totalLike: "360",
    title: "Digitalization/Conversion",
    image: "https://live.staticflickr.com/5258/5575237678_55a7d339ef_n.jpg",
  },
  {
    id: 5,
    category: "WEB DESIGN",
    totalLike: "280",
    title: "Design for tecnology & services",
    image: "https://th.bing.com/th/id/OIP.ZNDWwAGZPy8F6lRTjPKx_wHaEK?w=283&h=180&c=7&r=0&o=5&dpr=1.4&pid=1.7",
  },
  {
    id: 6,
    category: "WEB DESIGN",
    totalLike: "690",
    title: "App for tecnology & services",
    image: "https://i.pinimg.com/originals/d0/bf/71/d0bf712af39cc7bf9c5e1d5adcd31e2f.jpg",
  },
  {
    id: 6,
    category: "WEB DESIGN",
    totalLike: "690",
    title: "App for tecnology & services",
    image: "https://th.bing.com/th/id/OIP.ZNDWwAGZPy8F6lRTjPKx_wHaEK?w=283&h=180&c=7&r=0&o=5&dpr=1.4&pid=1.7",
  },
  {
    id: 6,
    category: "WEB DESIGN",
    totalLike: "690",
    title: "App for tecnology & services",
    image: "https://www.mechanicalpipingdesign.com/img/slides/Mech-design1.png",
  },
  {
    id: 6,
    category: "WEB DESIGN",
    totalLike: "690",
    title: "App for tecnology & services",
    image: "https://linedraw.b-cdn.net/images/329be0cb-4ee1-43a3-b5e4-eb31ffd0d768.jpg",
  },
  {
    id: 6,
    category: "WEB DESIGN",
    totalLike: "690",
    title: "App for tecnology & services",
    image: "https://www.scsgearbox.com/wp-content/uploads/2015/09/Bill-Leischner-Gearbox.jpg",
  },
]
export default Portfolio_data
